// Generated by CoffeeScript 1.12.7
(function() {
  var fs, multer;

  fs = require('fs');

  multer = require('multer');

  module.exports = function(req, res) {
    return new Promise(function(resolve, reject) {
      var storage, upload;
      storage = multer.diskStorage({
        destination: function(req, file, cb) {
          return cb(null, './upload/');
        },
        filename: function(req, file, cb) {
          if (/\/\\/.test(file.originalname)) {
            return cb(new Error("filename can\'t include \'\\\' or \'\/\'"));
          }
          if (fs.existsSync("./upload/" + file.originalname)) {
            return cb(new Error("The file has been uploaded"));
          }
          cb(null, file.originalname);
          return null;
        }
      });
      upload = multer({
        storage: storage
      }).any();
      return upload(req, res, function(err) {
        if (err) {
          return reject(err);
        } else {
          return resolve(err);
        }
      });
    });
  };

}).call(this);
