// Generated by CoffeeScript 2.3.2
(function() {
  var mod;

  mod = function(body) {
    var Arr, Par, ret;
    Arr = body.match(/Content-Length\:.*?\n\n(.*)/);
    if (!Arr) {
      return [];
    }
    Arr = Arr[1].split("&");
    Par = {};
    Arr.forEach(function(str) {
      var arr;
      arr = str.match(/^(.*?)=(.*?)$/);
      return Par[arr[1]] = arr[2];
    });
    return ret = [Par, Arr];
  };

  module.exports = mod;

}).call(this);
