// Generated by CoffeeScript 2.3.2
(function() {
  var mod;

  mod = function(requests) {
    var name;
    name = "";
    name += requests.ser_ip + "-";
    name += requests.time + "-";
    name += requests.method;
    if (requests.file !== null) {
      return name += "-file";
    }
  };

  module.exports = mod;

}).call(this);
