// Generated by CoffeeScript 2.3.2
(function() {
  var crypto;

  crypto = require('crypto');

  mod.Generator = function(pass) {
    var key, salt;
    salt = crypto.randomBytes(4096);
    key = crypto.pbkdf2Sync(pass, salt, 10000, 64, 'sha512');
    return [salt, key];
  };

  mod.Checker = function([pass, salt, key]) {
    var res;
    if (key === crypto.pbkdf2Sync(pass, salt, 10000, 64, 'sha512')) {
      res = true;
    } else {
      res = false;
    }
    return res;
  };

  module.exports = mod;

}).call(this);
