// Generated by CoffeeScript 1.12.7
(function() {
  var crypto;

  crypto = require('crypto');

  mod.Generator = function(pass) {
    var key, salt;
    salt = crypto.randomBytes(4096);
    key = crypto.pbkdf2Sync(pass, salt, 10000, 64, 'sha512');
    return [salt, key];
  };

  mod.Checker = function(arg) {
    var key, pass, res, salt;
    pass = arg[0], salt = arg[1], key = arg[2];
    if (key === crypto.pbkdf2Sync(pass, salt, 10000, 64, 'sha512')) {
      res = true;
    } else {
      res = false;
    }
    return res;
  };

  mod.LoginCookieGenerator = function(arg) {
    var Cookie, ip, key, random, random_hash, username;
    username = arg[0], key = arg[1], ip = arg[2];
    random = crypto.randomBytes(128);
    random_hash = crypto.pbkdf2Sync(random, username, 1, 64, 'sha512').toString("hex");
    Cookie = crypto.pbkdf2Sync("" + key + username + ip, random_hash, 100, 64, 'sha512');
    return [random_hash, Cookie.toString("hex")];
  };

  mod.LoginCookieChecker = function(arg) {
    var Cookie, ip, key, random_hash, res, server_Cookie, username;
    Cookie = arg[0], random_hash = arg[1], username = arg[2], key = arg[3], ip = arg[4];
    server_Cookie = crypto.pbkdf2Sync("" + key + username + ip, random_hash, 100, 64, 'sha512');
    if (Cookie === server_Cookie.toString("hex")) {
      res = true;
    } else {
      res = false;
    }
    return res;
  };

  module.exports = mod;

}).call(this);
